### PR TITLE
KE-27416 & SPARK-26605 fix executor token expired

### PR DESCRIPTION
**Pull request by weiwei121723**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by weiwei121723** [comment]
image

**Comment by weiwei121723** [comment]
retest this please

**Comment by weiwei121723** [comment]
retest this please

**Review by zheniantoushipashi — APPROVED** [review]

**Comment by weiwei121723** [comment]
retest this please

**Comment by weiwei121723** [comment]
retest this please

**Pull request merged**
