### PR TITLE
KE-42300 support split source partition

### PR DESCRIPTION
**Pull request by yugan95**

### CODE REVIEW

**Comment by yugan95** [comment]
retest this please

**Comment by zheniantoushipashi** [comment]
retest this please

**Comment by zheniantoushipashi** [comment]
retest this please

**Comment by lexmeng** [comment]
retest this please

**Comment by yugan95** [comment]
retest this please

**Comment by yugan95** [comment]
retest this please

**Comment by yugan95** [comment]
retest this please

**Comment by zheniantoushipashi** [comment]
retest this please

**Comment by pfzhan** [comment]
lgtm

**Review by zheniantoushipashi — APPROVED** [review]

**Pull request merged**
