### PR TITLE
[BACKPORT] log4j1 to log4j2 and change distribution management url

### PR DESCRIPTION
**Pull request by jiaoew1991**
## What changes were proposed in this pull request?

搬过来master分支上 log4j --> log4j2 相关的commit
删掉了老的基于 log4j1 写的appender

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by jiaoew1991** [comment]
retest this please

**Comment by jiaoew1991** [comment]
retest this please

**Comment by leejaywei** [comment]
retest this please

**Pull request closed without merging**
