### PR TITLE
KE-24858 Decimal precision problems cause the build to fail

### PR DESCRIPTION
**Pull request by jlfsdtc**
[BACKPORT]
[SPARK-28067][SQL] Fix incorrect results for decimal aggregate sum by returning null on decimal overflow
https://github.com/apache/spark/pull/27627
[SPARK-28067][SPARK-32018] Fix decimal overflow issues
https://github.com/apache/spark/pull/29026

### CODE REVIEW

**Comment by jlfsdtc** [comment]
retest this, please

**Comment by jlfsdtc** [comment]
retest this, please

**Comment by jlfsdtc** [comment]
retest this, please

**Review by zheniantoushipashi — APPROVED** [review]
LGTM

**Review by jiaoew1991 — APPROVED** [review]

**Pull request merged**
