### PR TITLE
KE-42784 Fix vulnerability, Upgrade org.apache.avro:avro to version 1.11.3

### PR DESCRIPTION
**Pull request by Mrhs121**

### CODE REVIEW

**Comment by yhcast0** [comment]
LGTM

**Comment by Mrhs121** [comment]
retest this please

**Comment by Mrhs121** [comment]
ut重跑两次都还过不了，需要排查一下原因

**Comment by Mrhs121** [comment]
retest this please

**Comment by Mrhs121** [comment]
retest this please

**Comment by Mrhs121** [comment]
环境问题，与版本升级无关，ut已过

**Review by zheniantoushipashi — APPROVED** [review]

**Review by zheniantoushipashi — APPROVED** [review]

**Pull request merged**
